codestates-seb/seb45_pre_013

- .gitignore
main branch의 변경사항을 어떻게 dev-front branch로 받아올수 있는지 고민만 하다가, 뒤늦게 검색해보니 답이 바로 나오더라고요...
main branch를 dev-front branch로 pull한 결과입니다.
타 브랜치의 데이터를 pull해오는 명령어를 확인한 참고자료도 공유합니다. https://potensj.tistory.com/90
이상없으면 12시에 같이 merge하겠습니다.
> Fe fix/pull branch main

- client/src/App.jsx
- client/src/components/ArticleTitle.jsx
- client/src/components/QuestionDetail/QuestionDetailLayout.jsx
- client/src/components/QuestionDetail/Vote.jsx
- client/src/components/QuestionList/QuestionItem.jsx
- client/src/components/QuestionList/QuestionListLayout.jsx
- client/src/components/QuestionWrite/WriteLayout.jsx
- client/src/components/Sidebar.jsx
- client/src/config/config.jsx
- client/src/pages/Home.jsx
- client/src/pages/Login.jsx
- client/src/pages/NotFound.jsx
- client/src/pages/QuestionDetail.jsx
- client/src/pages/Signup.jsx
- client/src/routers/Root.jsx
- client/src/styles/QuestionDetail/AnswerStyle.jsx
- client/src/styles/QuestionDetail/QuestionStyle.jsx
- client/src/styles/QuestionList/LayoutStyle.jsx
- client/src/styles/QuestionWriteStyle.jsx
- client/src/styles/RootStyle.jsx
연결되지 않은 페이지를 route하였고, root의 layout을 수정하였습니다.
question detail페이지의 key값을 config파일의 상수로 처리 하였습니다.
> router, layout 수정

- client/src/App.jsx
- client/src/components/QuestionWrite/WriteLayout.jsx
- client/src/components/RightSidebar.jsx
- client/src/routers/Root.jsx
- client/src/styles/Login/LoginFormStyle.jsx
- client/src/styles/QuestionDetail/AnswerStyle.jsx
- client/src/styles/QuestionDetail/QuestionStyle.jsx
- client/src/styles/QuestionDetail/VoteStyle.jsx
- client/src/styles/QuestionList/LayoutStyle.jsx
- client/src/styles/QuestionWriteStyle.jsx
- client/src/styles/RootStyle.jsx
- client/src/styles/SidebarStyle.jsx
- client/src/styles/TitleStyle.jsx
- client/src/styles/global.jsx
right sidebar 디자인 수정
css errfix
- footer 잘리는 문제
- button등 cursor: pointer로 변경
- span.link 스타일 global로 옮김
> Fe feat/right sidebar

- client/src/App.jsx
- client/src/components/MyPage/MyPagePreview.jsx
- client/src/components/Sidebar.jsx
MyPage와 EditProfile 페이지 routing하여 link로 연결한 수정본 브랜치입니다.
열홍님 수정본 올라오면 먼저 merge한 후 그 뒤 conflict일어날시 해결하며 merge하겠습니다.
> FE-feat/router MyPage&EditProfile

- server/overflow/build.gradle
- server/overflow/src/main/java/com/preproject/overflow/member/auth/filter/JwtAuthenticationFilter.java
- server/overflow/src/main/java/com/preproject/overflow/member/auth/filter/JwtVerificationFilter.java
- server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAccessDeniedHandler.java
- server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAuthenticationEntryPoint.java
- server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAuthenticationFailureHandler.java
- server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAuthenticationSuccessHandler.java
- server/overflow/src/main/java/com/preproject/overflow/member/auth/jwt/JwtTokenizer.java
- server/overflow/src/main/java/com/preproject/overflow/member/confing/SecurityConfiguration.java
- server/overflow/src/main/java/com/preproject/overflow/member/controller/MemberController.java
- server/overflow/src/main/java/com/preproject/overflow/member/dto/LoginDto.java
- server/overflow/src/main/java/com/preproject/overflow/member/dto/MemberPatchDto.java
- server/overflow/src/main/java/com/preproject/overflow/member/dto/MemberPostDto.java
- server/overflow/src/main/java/com/preproject/overflow/member/dto/MemberResponseDto.java
- server/overflow/src/main/java/com/preproject/overflow/member/entity/Member.java
- server/overflow/src/main/java/com/preproject/overflow/member/exception/BusinessLogicException.java
- server/overflow/src/main/java/com/preproject/overflow/member/exception/ExceptionCode.java
- server/overflow/src/main/java/com/preproject/overflow/member/exception/advice/GlobalExceptionAdvice.java
- server/overflow/src/main/java/com/preproject/overflow/member/exception/response/ErrorResponse.java
- server/overflow/src/main/java/com/preproject/overflow/member/mapper/MemberMapper.java
- server/overflow/src/main/java/com/preproject/overflow/member/repository/MemberRepository.java
- server/overflow/src/main/java/com/preproject/overflow/member/service/MemberDetailsService.java
- server/overflow/src/main/java/com/preproject/overflow/member/service/MemberService.java
- server/overflow/src/main/java/com/preproject/overflow/member/utils/CustomAuthorityUtils.java
- server/overflow/src/main/java/com/preproject/overflow/member/utils/ErrorResponder.java
- server/overflow/src/main/java/com/preproject/overflow/member/utils/RandomNumberGenerator.java
- server/overflow/src/main/resources/application.yml
> [BE] 회원가입/로그인 기능 구현 

- client/src/components/QuestionDetail/AnswerArticle.jsx
- client/src/components/QuestionDetail/AnswerForm.jsx
- client/src/components/QuestionDetail/QuestionDetailLayout.jsx
- client/src/main.jsx
- client/src/store/store.js
> answer create

- server/overflow/src/main/java/com/preproject/overflow/answer/controller/AnswerController.java
- server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
> [feat] 응답값 닉네임 포함 가능하게 수정

- server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
- server/overflow/src/main/java/com/preproject/overflow/exception/BusinessLogicException.java
- server/overflow/src/main/java/com/preproject/overflow/exception/ExceptionCode.java
- server/overflow/src/main/java/com/preproject/overflow/exception/advice/GlobalExceptionAdvice.java
- server/overflow/src/main/java/com/preproject/overflow/exception/response/ErrorResponse.java
- server/overflow/src/main/java/com/preproject/overflow/member/service/MemberDetailsService.java
- server/overflow/src/main/java/com/preproject/overflow/member/service/MemberService.java
- server/overflow/src/main/java/com/preproject/overflow/member/utils/ErrorResponder.java
- server/overflow/src/main/resources/application.yml
> [BE-fix] Excetion 패키지 수정

- server/overflow/src/main/java/com/preproject/overflow/answer/controller/AnswerController.java
- server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerPatchDto.java
- server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerPostDto.java
- server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
- server/overflow/src/main/java/com/preproject/overflow/member/confing/SecurityConfiguration.java
답변 생성 시 로그인된 사용자인지 확인 후 생성
AnswerPatchDto memberId, getMemberId(), setMemberId 삭제
AnswerPostDto memberId, getMemberId(), setMemberId, getMember() 삭제
SecurityConfiguration HttpMethod.POST, "/answers/" 권한 추가
AnswerService updateAnswer, deleteAnswer 예외처리 ExceptionCode 수정, 주석 삭제
> [feat] 답변 생성 권한 확인 구현

- server/overflow/src/main/java/com/preproject/overflow/question/controller/QuestionController.java
- server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionResponseDto.java
- server/overflow/src/main/java/com/preproject/overflow/question/entity/Question.java
- server/overflow/src/main/java/com/preproject/overflow/question/mapper/QuestionMapper.java
> [BE-feat] Question 기능 추가 구현

- server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
답변 생성 시 AnswerCount 올라가도록 구현했습니다.
> [feat] 답변 생성 시 AnswerCount 올라가도록 구현

- client/src/components/Modal.jsx
- client/src/components/QuestionWrite/WriteLayout.jsx
- client/src/styles/ModalStyle.jsx
> Fe feat/write pageform구현

- server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
답변 삭제 시 AnswerCount 내려가도록 구현했습니다.
> [feat] 답변 삭제 시 AnswerCount 내려가도록 구현

- client/src/components/Sidebar.jsx
> sidebar(Login,Signup-selectedPage오류수정)

- client/.gitignore
- client/src/components/Modal.jsx
- client/src/components/QuestionDetail/AnswerArticle.jsx
- client/src/components/QuestionDetail/AnswerForm.jsx
- client/src/components/QuestionDetail/QuestionDetailLayout.jsx
- client/src/components/QuestionList/QuestionItem.jsx
- client/src/components/QuestionList/QuestionListLayout.jsx
- client/src/components/QuestionWrite/WriteLayout.jsx
- client/src/config/config.jsx
- client/src/store/slice/detailSlice.jsx
- client/src/store/slice/questionSlice.jsx
- client/src/store/slice/slice.js
- client/src/store/store.js
questionSlice 생성
**config** 
(view,answer,vote,user_name) 서버데이터와 다르기에 값 수정
QUESTIONID = "questionId";
QUESTIONTAGLIST = "questionTagList";
누락부분 추가
components
**QuestionList**
서버연결 완료
**QuestionDetail**
테스트용 코드 제거 후 서버와 연결 완료
삭제와 수정  미구현
**QuestionWrite**
서버로 입력값 전송은 되었지만
아직 데이터베이스 추가는 미완성 되었음
> Fe feat/question/list,deatil,write

- .idea/compiler.xml
- server/overflow/src/main/java/com/preproject/overflow/question/controller/QuestionController.java
- server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionPatchDto.java
- server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionPostDto.java
- server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionResponseDto.java
- server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionTagDto.java
- server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionTagResponseDto.java
- server/overflow/src/main/java/com/preproject/overflow/question/entity/Question.java
- server/overflow/src/main/java/com/preproject/overflow/question/entity/QuestionTag.java
- server/overflow/src/main/java/com/preproject/overflow/question/mapper/QuestionMapper.java
- server/overflow/src/main/java/com/preproject/overflow/question/repository/QuestionTagRepository.java
- server/overflow/src/main/java/com/preproject/overflow/question/service/QuestionService.java
- server/overflow/src/main/java/com/preproject/overflow/question/service/QuestionTagService.java
- server/overflow/src/main/java/com/preproject/overflow/tag/controller/TagController.java
- server/overflow/src/main/java/com/preproject/overflow/tag/dto/TagDto.java
- server/overflow/src/main/java/com/preproject/overflow/tag/entity/Tag.java
- server/overflow/src/main/java/com/preproject/overflow/tag/mapper/TagMapper.java
- server/overflow/src/main/java/com/preproject/overflow/tag/repository/TagRepository.java
- server/overflow/src/main/java/com/preproject/overflow/tag/service/TagService.java
> [feat] questionTag기능 삭제

- server/overflow/Dockerfile
- server/overflow/src/main/java/com/preproject/overflow/member/confing/SecurityConfiguration.java
- server/overflow/src/main/resources/application.yml
> [BE-server] 배포 설정 

- server/overflow/src/main/resources/application.yml
데이터베이스 ddl-auto 방식 변경 - create-drop -> update
> [BE-Server] 데이터 베이스 설정

- client/src/components/Modal.jsx
- client/src/components/QuestionDetail/AnswerArticle.jsx
- client/src/components/QuestionDetail/QuestionDetailLayout.jsx
- client/src/components/QuestionList/QuestionItem.jsx
- client/src/components/QuestionWrite/WriteLayout.jsx
- client/src/store/slice/questionSlice.jsx
- client/src/store/slice/slice.js
- client/src/styles/ModalStyle.jsx
- client/src/styles/QuestionWriteStyle.jsx
- client/src/styles/TitleStyle.jsx
리스트 조회,질문상세 페이지 멤버사진조회 에러해결
질문 등록 에러 해결
삭제,수정 버튼 리스트페이지 연결로 인해 해결하지 못함
> Fe fix/apierrorclearend

- client/src/store/slice/slice.js
> answer delete fix

- client/src/components/QuestionDetail/QuestionDetailLayout.jsx
- client/src/components/QuestionWrite/WriteLayout.jsx
- client/src/store/slice/detailSlice.jsx
- client/src/styles/DivStyle.jsx
- client/src/styles/QuestionDetail/QuestionStyle.jsx
questionDetail 페이지 delete,modify 버튼 및 기능 구현 완료
> Fe feat/button/del,modify
